### ISSUE TITLE
Install cluster failed with some mediums 

### ISSUE THREAD

**Issue by uvrds** [ytsaurus/ytsaurus-k8s-operator#322]
When I try install cluster first time with mediums ssd and hdd. I got error: 
`kubectl -n yt-lt01 logs yt-queue-agent-init-job-qa-state-jpxjq  
++ export YT_DRIVER_CONFIG_PATH=/config/client.yson
++ YT_DRIVER_CONFIG_PATH=/config/client.yson
+++ /usr/bin/ytserver-all --version
+++ head -c4
++ export YTSAURUS_VERSION=24.1
++ YTSAURUS_VERSION=24.1
++ [[ -f /usr/bin/init_queue_agent_state ]]
++ /usr/bin/init_queue_agent_state --create-registration-table --create-replicated-table-mapping-table --recursive --ignore-existing --proxy http-proxies.yt-lt01.svc.cluster.local
Traceback (most recent call last):
  File "/usr/bin/init_queue_agent_state", line 185, in <module>
    main()
  File "/usr/bin/init_queue_agent_state", line 170, in main
    create_tables(client,
  File "/usr/bin/init_queue_agent_state", line 109, in create_tables
    create_table(client, "{}/{}".format(root, DEFAULT_QUEUE_TABLE_NAME), queue_table_schema, tablet_cell_bundle, **kwargs)
  File "/usr/bin/init_queue_agent_state", line 85, in create_table
    client.mount_table(path, sync=True)
  File "/usr/local/lib/python3.8/dist-packages/yt/wrapper/client_impl.py", line 1476, in mount_table
    return client_api.mount_table(
  File "/usr/local/lib/python3.8/dist-packages/yt/wrapper/dynamic_table_commands.py", line 529, in mount_table
    response = make_request("mount_table", params, client=client)
  File "/usr/local/lib/python3.8/dist-packages/yt/wrapper/driver.py", line 114, in make_request
    result = http_driver.make_request(
  File "<decorator-gen-3>", line 2, in make_request
  File "/usr/local/lib/python3.8/dist-packages/yt/wrapper/common.py", line 453, in forbidden_inside_job
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yt/wrapper/http_driver.py", line 283, in make_request
    response = make_request_with_retries(
  File "/usr/local/lib/python3.8/dist-packages/yt/wrapper/http_helpers.py", line 472, in make_request_with_retries
    return RequestRetrier(method=method, url=url, **kwargs).run()
  File "/usr/local/lib/python3.8/dist-packages/yt/wrapper/retries.py", line 89, in run
    return self.action()
  File "/usr/local/lib/python3.8/dist-packages/yt/wrapper/http_helpers.py", line 427, in action
    _raise_for_status(response, request_info)
  File "/usr/local/lib/python3.8/dist-packages/yt/wrapper/http_helpers.py", line 307, in _raise_for_status
    raise error_exc
yt.common.YtResponseError: Error committing transaction 4-24ef-10009-a90d39eb
    Error committing transaction 4-24ef-10009-a90d39eb at cell 65726e65-ad6b7562-10259-79747361
        No healthy tablet cells in bundle "sys"
* Details:
Received HTTP response with error    
    origin          yt-queue-agent-init-job-qa-state-jpxjq on 2024-08-07T15:37:31.508409Z    
    url             http://http-proxies.yt-lt01.svc.cluster.local/api/v4/mount_table    
    request_headers {
                      "User-Agent": "Python wrapper 0.13-dev-f6622682d3810dd8972be1739e678821541ae80e",
                      "Accept-Encoding": "gzip, identity",
                      "X-Started-By": "{\"pid\"=11;\"user\"=\"root\";}",
                      "X-YT-Header-Format": "<format=text>yson",
                      "Content-Type": "application/x-yt-yson-text",
                      "X-YT-Correlation-Id": "730a7696-1a96ce63-5b39ea6c-1c956520"
                    }    
    response_headers {
                      "Content-Length": "1295",
                      "X-YT-Response-Message": "Error committing transaction 4-24ef-10009-a90d39eb",
                      "X-YT-Response-Code": "1",
                      "X-YT-Response-Parameters": {},
                      "X-YT-Trace-Id": "fe4b8d75-e05a20ee-b2606ba-d3c45fe9",
                      "X-YT-Error": "{\"code\":1,\"message\":\"Error committing transaction 4-24ef-10009-a90d39eb\",\"attributes\":{\"host\":\"hp-0.http-proxies.yt-lt01.svc.cluster.local\",\"pid\":1,\"tid\":6392000469809232264,\"thread\":\"RpcLight\",\"fid\":18446444482693395676,\"datetime\":\"2024-08-07T15:37:31.504665Z\",\"trace_id\":\"fe4b8d75-e05a20ee-b2606ba-d3c45fe9\",\"span_id\":15491716624836717466,\"cluster_id\":\"Native(Name=yt)\",\"path\":\"//sys/queue_agents/queues\"},\"inner_errors\":[{\"code\":1,\"message\":\"Error committing transaction 4-24ef-10009-a90d39eb at cell 65726e65-ad6b7562-10259-79747361\",\"attributes\":{\"host\":\"hp-0.http-proxies.yt-lt01.svc.cluster.local\",\"pid\":1,\"tid\":6392000469809232264,\"thread\":\"RpcLight\",\"fid\":18446444482693395676,\"datetime\":\"2024-08-07T15:37:31.504192Z\",\"trace_id\":\"fe4b8d75-e05a20ee-b2606ba-d3c45fe9\",\"span_id\":15491716624836717466},\"inner_errors\":[{\"code\":1,\"message\":\"No healthy tablet cells in bundle \\\"sys\\\"\",\"attributes\":{\"datetime\":\"2024-08-07T15:37:31.490331Z\",\"request_id\":\"dff61471-5e345995-11205302-8d0c33ac\",\"connection_id\":\"ef83239f-e7172c2-510ad6c9-e9b865d0\",\"verification_mode\":\"none\",\"realm_id\":\"65726e65-ad6b7562-10259-79747361\",\"timeout\":30000,\"method\":\"CommitTransaction\",\"address\":\"ms-2.masters.yt-lt01.svc.cluster.local:9010\",\"encryption_mode\":\"optional\",\"service\":\"TransactionSupervisorService\"}}]}]}",
                      "X-YT-Request-Id": "fba92ce8-cc1220c3-b7f3d9e8-ed909cc5",
                      "Content-Type": "application/json",
                      "Cache-Control": "no-store",
                      "X-YT-Proxy": "hp-0.http-proxies.yt-lt01.svc.cluster.local",
                      "Authorization": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                    }    
    params          {
                      "suppress_transaction_coordinator_sync": false,
                      "path": "//sys/queue_agents/queues",
                      "freeze": false,
                      "mutation_id": "8276fc5c-e5282f1e-2b5632c0-b10c6de2",
                      "retry": false
                    }    
    transparent     True
Error committing transaction 4-24ef-10009-a90d39eb    
    origin          hp-0.http-proxies.yt-lt01.svc.cluster.local on 2024-08-07T15:37:31.504665Z (pid 1, tid 58b4f28f9f1bf988, fid fffeef8607e774dc)    
    thread          RpcLight    
    trace_id        fe4b8d75-e05a20ee-b2606ba-d3c45fe9    
    span_id         15491716624836717466    
    cluster_id      Native(Name=yt)    
    path            //sys/queue_agents/queues
Error committing transaction 4-24ef-10009-a90d39eb at cell 65726e65-ad6b7562-10259-79747361    
    origin          hp-0.http-proxies.yt-lt01.svc.cluster.local on 2024-08-07T15:37:31.504192Z (pid 1, tid 58b4f28f9f1bf988, fid fffeef8607e774dc)    
    thread          RpcLight    
    trace_id        fe4b8d75-e05a20ee-b2606ba-d3c45fe9    
    span_id         15491716624836717466

No healthy tablet cells in bundle "sys"    
    origin          yt-queue-agent-init-job-qa-state-jpxjq on 2024-08-07T15:37:31.490331Z    
    request_id      dff61471-5e345995-11205302-8d0c33ac    
    connection_id   ef83239f-e7172c2-510ad6c9-e9b865d0    
    verification_mode none    
    realm_id        65726e65-ad6b7562-10259-79747361    
    timeout         30000    
    method          CommitTransaction    
    address         ms-2.masters.yt-lt01.svc.cluster.local:9010    
    encryption_mode optional    
    service         TransactionSupervisorService
...`
config:
`  dataNodes:
    - instanceCount: 2
      resources:
        limits:
          cpu: 2
          memory: 4Gi
      name: "ssd"
      volumeMounts:
        - name: chunk-store-ssd
          mountPath: /yt/data-nodes/node-chunk-store-ssd
      locations:
        - locationType: ChunkStore
          medium: ssd_blobs
          path: /yt/data-nodes/node-chunk-store-ssd
      volumeClaimTemplates:
        - metadata:
            name: chunk-store-ssd
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 30Gi

    - instanceCount: 1
      resources:
        limits:
          cpu: 2
          memory: 4Gi
      name: "hdd"
      volumeMounts:
        - name: chunk-store-hdd
          mountPath: /yt/data-nodes/node-chunk-store-hdd
      locations:
        - locationType: ChunkStore
          medium: default
          path: /yt/data-nodes/node-chunk-store-hdd
      volumeClaimTemplates:
          - metadata:
              name: chunk-store-hdd
            spec:
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 30Gi`

**Comment by koct9i** [comment]
> No healthy tablet cells in bundle "sys"

Duplicate for tablet cell bundle initialization fixup
